<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Daniel" name="Section17_TestNG.A5_Annotations" tests="4" failures="1" timestamp="24 May 2019 03:34:13 GMT" time="3.039" errors="0">
  <testcase name="method2" time="0.011" classname="Section17_TestNG.A5_Annotations"/>
  <testcase name="timeOutExample" time="3.015" classname="Section17_TestNG.A5_Annotations">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.timeOutExample() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.timeOutExample() didn't finish within the time-out 3000
	at java.util.concurrent.ThreadPoolExecutor.afterExecute(ThreadPoolExecutor.java:1989)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- timeOutExample -->
  <testcase name="method1" time="0.007" classname="Section17_TestNG.A5_Annotations"/>
  <testcase name="wmethod1" time="0.006" classname="Section17_TestNG.A5_Annotations"/>
</testsuite> <!-- Section17_TestNG.A5_Annotations -->
